[SPARK-42524][BUILD] Upgrade numpy and pandas in the release Dockerfile
### What changes were proposed in this pull request?
Upgrade pandas from 1.1.5 to 1.5.3, numpy from 1.19.4 to 1.20.3 in the Dockerfile used for Spark releases.

They are also what we use to cut `v3.4.0-rc1`.

### Why are the changes needed?
Otherwise, errors are raised as shown below when building release docs.
```
ImportError: Warning: Latest version of pandas (1.5.3) is required to generate the documentation; however, your version was 1.1.5

ImportError: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.4.
Please upgrade numpy to >= 1.20.3 to use this pandas version
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manual tests.

Closes #40111 from xinrong-meng/docker_lib.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit d09742b955782fc9717aaa0a76f067ccdf241010)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>