[SPARK-42378][CONNECT][PYTHON] Make `DataFrame.select` support `a.*`
### What changes were proposed in this pull request?
Make `DataFrame.select` support `a.*`

### Why are the changes needed?
bugfix:
```
Traceback (most recent call last):
  File "/Users/ruifeng.zheng/Dev/spark/python/pyspark/sql/tests/connect/test_connect_basic.py", line 1377, in test_select_star
    cdf.select("a", "b.*").collect(),
  File "/Users/ruifeng.zheng/Dev/spark/python/pyspark/sql/connect/dataframe.py", line 1305, in collect
    table = self._session.client.to_table(query)
  File "/Users/ruifeng.zheng/Dev/spark/python/pyspark/sql/connect/client.py", line 445, in to_table
    table, _ = self._execute_and_fetch(req)
  File "/Users/ruifeng.zheng/Dev/spark/python/pyspark/sql/connect/client.py", line 639, in _execute_and_fetch
    self._handle_error(rpc_error)
  File "/Users/ruifeng.zheng/Dev/spark/python/pyspark/sql/connect/client.py", line 675, in _handle_error
    raise SparkConnectAnalysisException(
pyspark.errors.exceptions.SparkConnectAnalysisException: [FIELD_NOT_FOUND] No such struct field `*` in `c`, `d`.
```

### Does this PR introduce _any_ user-facing change?
yes

### How was this patch tested?
added ut

Closes #39934 from zhengruifeng/connect_select_star.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>
(cherry picked from commit dbc4c621679318e0652a00aec54927b5659d65cd)
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>