[SPARK-42765][CONNECT][PYTHON] Enable importing `pandas_udf` from `pyspark.sql.connect.functions`
### What changes were proposed in this pull request?
Enable users to import pandas_udf via `pyspark.sql.connect.functions.pandas_udf`.
Previously, only `pyspark.sql.functions.pandas_udf` is supported.

### Why are the changes needed?
Usability.

### Does this PR introduce _any_ user-facing change?
Yes. Now users can import pandas_udf via `pyspark.sql.connect.functions.pandas_udf`.

Previously only `pyspark.sql.functions.pandas_udf` is supported in Connect; importing `pyspark.sql.connect.functions.pandas_udf` raises an error instead, as shown below

```sh
>>> pyspark.sql.connect.functions.pandas_udf()
Traceback (most recent call last):
...
NotImplementedError: pandas_udf() is not implemented.
```

Now, `pyspark.sql.connect.functions.pandas_udf` point to `pyspark.sql.functions.pandas_udf`, as shown below,
```sh
>>> from pyspark.sql.connect import functions as CF
>>> from pyspark.sql import functions as SF
>>> getattr(CF, "pandas_udf")
<function pandas_udf at 0x7f9c88812700>
>>> getattr(SF, "pandas_udf")
<function pandas_udf at 0x7f9c88812700>
```

### How was this patch tested?
Unit test.

Closes #40388 from xinrong-meng/rmv_path.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 149e020a5ca88b2db9c56a9d48e0c1c896b57069)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>