[SPARK-42917][SQL] Correct getUpdateColumnNullabilityQuery for DerbyDialect
### What changes were proposed in this pull request?

Fix nullability clause for derby dialect, according to the official derby lang ref guide.

### Why are the changes needed?

To fix bugs like:
```
spark-sql ()> create table src2(ID INTEGER NOT NULL, deptno INTEGER NOT NULL);
spark-sql ()> alter table src2 ALTER COLUMN ID drop not null;

java.sql.SQLSyntaxErrorException: Syntax error: Encountered "NULL" at line 1, column 42.
```

### Does this PR introduce _any_ user-facing change?

yes, but a necessary bugfix

### How was this patch tested?

Test manually.

Closes #40544 from yaooqinn/SPARK-42917.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Kent Yao <yao@apache.org>
(cherry picked from commit bcadbb69be6ac9759cb79fc4ee7bd93a37a63277)
Signed-off-by: Kent Yao <yao@apache.org>