[SPARK-42253][PYTHON] Add test for detecting duplicated error class
### What changes were proposed in this pull request?

This PR proposes to add test for detecting duplicated name of error classes to keep the error class unique.

### Why are the changes needed?

The name of error class should be unique, so we should check if it's duplicated or not.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually test in case `COLUMN_IN_LIST` is duplicated as below:
```shell
======================================================================
FAIL [0.006s]: test_error_classes_duplicated (pyspark.errors.tests.test_errors.ErrorsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
AssertionError: False is not true : Duplicate error class: COLUMN_IN_LIST

----------------------------------------------------------------------
Ran 2 tests in 0.007s

FAILED (failures=1)
```

Closes #39821 from itholic/SPARK-42253.

Lead-authored-by: itholic <haejoon.lee@databricks.com>
Co-authored-by: Hyukjin Kwon <gurwls223@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 4d37e7816ce83dc5928b0d42a536304cb49eb0a3)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>