[SPARK-44557][INFRA] Clean up untracked/ignored files before running pip packaging test in GitHub Actions
### What changes were proposed in this pull request?

This PR proposes to remove untracked/ignored files before running pip packaging test in GitHub Actions.

### Why are the changes needed?

In order to fix the flakiness in the test such as:

```
...
creating dist
Creating tar archive
error: [Errno 28] No space left on device
Cleaning up temporary directory - /tmp/tmp.CvSzgB7Kyy
```

See also https://github.com/apache/spark/actions/runs/5665869112/job/15351515539.

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

GitHub Actions build in this PR.

Closes #42159 from HyukjinKwon/debug-ci-failure.

Lead-authored-by: Hyukjin Kwon <gurwls223@apache.org>
Co-authored-by: Hyukjin Kwon <gurwls223@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 77aab6edb7c2b7be54cb19d40c0eeeb2c699f0f7)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>