rdar://114672798: Don't load Boson jar in Spark unless Boson is enabled (#1850)
Some users wanted to exclude Boson jar in their Spark distribution to reduce the total binary size, but at the moment this is not possible:

```
Caused by: java.lang.NoClassDefFoundError: com/apple/boson/BosonConf$
	at org.apache.spark.sql.SparkSession$.loadBosonExtension(SparkSession.scala:1239) ~[spark-sql_2.12-3.3.0.51-apple.jar:3.3.0.51-apple]
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$applyExtensions(SparkSession.scala:1254) ~[spark-sql_2.12-3.3.0.51-apple.jar:3.3.0.51-apple]
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:973) ~[spark-sql_2.12-3.3.0.51-apple.jar:3.3.0.51-apple]
```

This patch removes hard-coded `BosonConf` config key and `BosonScanExec`. For `BosonConf`, we simply use the string of the config. For `BosonScanExec`, we check if `BosonScanExec` is loadable before accessing the instance as `BosonScanExec`.

To test it, I make `boson` dependency as `provided` manually in local and run `spark-shell` with Boson enabled so Spark cannot find Boson dependency:

```
BOSON=true bin/spark-shell --master "local[1]" --driver-memory 2g                                                                                                                            
23/08/29 18:32:30 WARN Utils: Your hostname, Liang-Chis-MacBook-Pro-4.local resolves to a loopback address: 127.0.0.1; using 192.168.86.32 instead (on interface en0)
23/08/29 18:32:30 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".                                                                               
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
23/08/29 18:32:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
23/08/29 18:32:33 WARN SparkSession: Cannot use com.apple.boson.BosonSparkSessionExtensions to configure session extensions.
java.lang.ClassNotFoundException: com.apple.boson.BosonSparkSessionExtensions
        at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:72)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)               
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)                                 
        at java.base/java.lang.Class.forName0(Native Method)                                                                                                                                                                           
        at java.base/java.lang.Class.forName(Class.java:398)                                    
        at org.apache.spark.util.Utils$.classForName(Utils.scala:225)                  
```

Spark basically just logs a warn when it cannot load a `SessionExtension` so it won't fail the application.