[SPARK-42899][SQL] Fix DataFrame.to(schema) to handle the case where there is a non-nullable nested field in a nullable field
Fixes `DataFrame.to(schema)` to handle the case where there is a non-nullable nested field in a nullable field.

`DataFrame.to(schema)` fails when it contains non-nullable nested field in nullable field:

```scala
scala> val df = spark.sql("VALUES (1, STRUCT(1 as i)), (NULL, NULL) as t(a, b)")
df: org.apache.spark.sql.DataFrame = [a: int, b: struct<i: int>]
scala> df.printSchema()
root
 |-- a: integer (nullable = true)
 |-- b: struct (nullable = true)
 |    |-- i: integer (nullable = false)

scala> df.to(df.schema)
org.apache.spark.sql.AnalysisException: [NULLABLE_COLUMN_OR_FIELD] Column or field `b`.`i` is nullable while it's required to be non-nullable.
```

No.

Added the related tests.

Closes #40526 from ueshin/issues/SPARK-42899/to_schema.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 4052058f9d1f60f1539dd227614cd459bfdfd31f)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>