[SPARK-42522][CONNECT] Fix DataFrameWriterV2 to find the default source
### What changes were proposed in this pull request?

Fixes `DataFrameWriterV2` to find the default source.

### Why are the changes needed?

Currently `DataFrameWriterV2` in Spark Connect doesn't work without the provider with a weird error:

For example:

```py
df.writeTo("test_table").create()
```

```
pyspark.errors.exceptions.connect.SparkConnectGrpcException: (org.apache.spark.SparkClassNotFoundException) [DATA_SOURCE_NOT_FOUND] Failed to find the data source: . Please find packages at `https://spark.apache.org/third-party-projects.html`.
```

### Does this PR introduce _any_ user-facing change?

Users will be able to use `DataFrameWriterV2` without provider as same as PySpark.

### How was this patch tested?

Added some tests.

Closes #40109 from ueshin/issues/SPARK-42522/writer_v2.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Herman van Hovell <herman@databricks.com>
(cherry picked from commit dbe23c8e88d1a2968ae1c17ec9ee3029ef7a348a)
Signed-off-by: Herman van Hovell <herman@databricks.com>